apiVersion: v1
kind: ConfigMap
metadata:
  name: xray-config
  namespace: xray
data:
  config.json: |
    {
        "log": {
            "loglevel": "warning"
        },
        "inbounds": [
            {
                "port": 8080,
                "listen": "0.0.0.0",
                "protocol": "vless",
                "settings": {
                    "clients": [
                        {
                            "id": "", // 填写你的 UUID
                            "level": 0,
                            "email": "love@example.com"
                        }
                    ],
                    "decryption": "none"
                },
                "streamSettings": {
                    "network": "ws",
                    "security": "none",
                    "wsSettings": {
                        // "acceptProxyProtocol": true, // 提醒：若你用 Nginx/Caddy 等反代 WS，需要删掉这行
                        "path": "/xray" // 必须换成自定义的 PATH，需要和上面的一致
                    }
                }
            }
        ],
        "outbounds": [
            {
                "protocol": "freedom"
            }
        ]
    }
